version: "3.8"

services:
  go-ping-1:
    build:
      context: ./server1
    container_name: go-ping-1
    ports:
      - "6980:6980"
    restart: always

  go-ping-2:
    build:
      context: ./server2
    container_name: go-ping-2
    ports:
      - "8069:8069"
    restart: always
